// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuUwODLNwZ-M3WI9WyuK3pOQUXkMUo5dA',
    appId: '1:883005184689:android:0f3227f98c0b14f196e090',
    messagingSenderId: '883005184689',
    projectId: 'medai-3ce9c',
    storageBucket: 'medai-3ce9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA53_LUSOvraE2_j5KIqjrc4T_tmVkg9kc',
    appId: '1:883005184689:ios:73d1061bb98980e996e090',
    messagingSenderId: '883005184689',
    projectId: 'medai-3ce9c',
    storageBucket: 'medai-3ce9c.firebasestorage.app',
    iosBundleId: 'com.medtracker.medtrackaiflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA53_LUSOvraE2_j5KIqjrc4T_tmVkg9kc',
    appId: '1:883005184689:ios:73d1061bb98980e996e090',
    messagingSenderId: '883005184689',
    projectId: 'medai-3ce9c',
    storageBucket: 'medai-3ce9c.firebasestorage.app',
    iosBundleId: 'com.medtracker.medtrackaiflutter',
  );
}
